// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-10-08
//
// CostPer1MChars is per 1M characters, in the currency the provider
// bills in. Default format and latency are not published and are
// carried over from the previous catalog.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.
//
// OpenRouter routes to upstream providers and passes their rates
// through; the figures here are the ones it quotes.

package openrouter

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Model IDs served by this catalog.
const (
	SeedAudio10            string = "openrouter.seed-audio-1-0"
	Orpheus3B              string = "openrouter.orpheus-3b-0.1-ft"
	Aura2                  string = "openrouter.aura-2"
	FluxTTS                string = "openrouter.flux-tts"
	ElevenFlashV2          string = "openrouter.eleven-flash-v2"
	ElevenFlashV25         string = "openrouter.eleven-flash-v2.5"
	ElevenMultilingualV2   string = "openrouter.eleven-multilingual-v2"
	ElevenTurboV2          string = "openrouter.eleven-turbo-v2"
	ElevenTurboV25         string = "openrouter.eleven-turbo-v2.5"
	ElevenV3               string = "openrouter.eleven-v3"
	ElevenV3Conversational string = "openrouter.eleven-v3-conversational"
	ElevenV4               string = "openrouter.eleven-v4"
	ElevenV4Turbo          string = "openrouter.eleven-v4-turbo"
	FishAudioS1            string = "openrouter.s1"
	FishAudioS2Pro         string = "openrouter.s2-pro"
	FishAudioS21Pro        string = "openrouter.s2.1-pro"
	S21ProFreeFree         string = "openrouter.s2.1-pro-free-free"
	Gemini31FlashTTS       string = "openrouter.gemini-3.1-flash-tts-preview"
	Gemini38FlashLiteTTS   string = "openrouter.gemini-3.8-flash-lite-tts"
	Gemini38FlashTTS       string = "openrouter.gemini-3.8-flash-tts"
	Kokoro82M              string = "openrouter.kokoro-82m"
	MAIVoice2              string = "openrouter.mai-voice-2"
	MAIVoice2Flash         string = "openrouter.mai-voice-2-flash"
	MaiVoice21             string = "openrouter.mai-voice-2.1"
	MaiVoice21Flash        string = "openrouter.mai-voice-2.1-flash"
	MiniMaxSpeech28HD      string = "openrouter.speech-2.8-hd"
	MiniMaxSpeech28Turbo   string = "openrouter.speech-2.8-turbo"
	VoxtralMiniTTS         string = "openrouter.voxtral-mini-tts-2603"
	QwenAudio3TTSFlash     string = "openrouter.qwen-audio-3.0-tts-flash"
	QwenAudio3TTSPlus      string = "openrouter.qwen-audio-3.0-tts-plus"
	CSM1B                  string = "openrouter.csm-1b"
	GrokVoiceTTS1          string = "openrouter.grok-voice-tts-1.0"
)

// Models maps model IDs to their configurations.
var Models = map[string]tts.AudioModel{
	SeedAudio10: {
		ID:       SeedAudio10,
		Name:     "OpenRouter – Seed Audio 1.0",
		Provider: "openrouter",
		APIModel: "bytedance-seed/seed-audio-1-0",
		Currency: "USD",
	},
	Orpheus3B: {
		ID:               Orpheus3B,
		Name:             "OpenRouter – Orpheus 3B",
		Provider:         "openrouter",
		APIModel:         "canopylabs/orpheus-3b-0.1-ft",
		Currency:         "USD",
		CostPer1MChars:   7,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	Aura2: {
		ID:               Aura2,
		Name:             "OpenRouter – Aura-2",
		Provider:         "openrouter",
		APIModel:         "deepgram/aura-2",
		Currency:         "USD",
		CostPer1MChars:   30,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	FluxTTS: {
		ID:       FluxTTS,
		Name:     "OpenRouter – Flux TTS",
		Provider: "openrouter",
		APIModel: "deepgram/flux-tts",
		Currency: "USD",
	},
	ElevenFlashV2: {
		ID:       ElevenFlashV2,
		Name:     "OpenRouter – Eleven Flash v2",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-flash-v2",
		Currency: "USD",
	},
	ElevenFlashV25: {
		ID:       ElevenFlashV25,
		Name:     "OpenRouter – Eleven Flash v2.5",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-flash-v2.5",
		Currency: "USD",
	},
	ElevenMultilingualV2: {
		ID:       ElevenMultilingualV2,
		Name:     "OpenRouter – Eleven Multilingual v2",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-multilingual-v2",
		Currency: "USD",
	},
	ElevenTurboV2: {
		ID:       ElevenTurboV2,
		Name:     "OpenRouter – Eleven Turbo v2",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-turbo-v2",
		Currency: "USD",
	},
	ElevenTurboV25: {
		ID:       ElevenTurboV25,
		Name:     "OpenRouter – Eleven Turbo v2.5",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-turbo-v2.5",
		Currency: "USD",
	},
	ElevenV3: {
		ID:       ElevenV3,
		Name:     "OpenRouter – Eleven v3",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-v3",
		Currency: "USD",
	},
	ElevenV3Conversational: {
		ID:       ElevenV3Conversational,
		Name:     "OpenRouter – Eleven v3 Conversational",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-v3-conversational",
		Currency: "USD",
	},
	ElevenV4: {
		ID:       ElevenV4,
		Name:     "OpenRouter – Eleven v4",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-v4",
		Currency: "USD",
	},
	ElevenV4Turbo: {
		ID:       ElevenV4Turbo,
		Name:     "OpenRouter – Eleven v4 Turbo",
		Provider: "openrouter",
		APIModel: "elevenlabs/eleven-v4-turbo",
		Currency: "USD",
	},
	FishAudioS1: {
		ID:               FishAudioS1,
		Name:             "OpenRouter – S1",
		Provider:         "openrouter",
		APIModel:         "fish-audio/s1",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	FishAudioS2Pro: {
		ID:               FishAudioS2Pro,
		Name:             "OpenRouter – S2 Pro",
		Provider:         "openrouter",
		APIModel:         "fish-audio/s2-pro",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	FishAudioS21Pro: {
		ID:               FishAudioS21Pro,
		Name:             "OpenRouter – S2.1 Pro",
		Provider:         "openrouter",
		APIModel:         "fish-audio/s2.1-pro",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	S21ProFreeFree: {
		ID:       S21ProFreeFree,
		Name:     "OpenRouter – S2.1 Pro Free (free)",
		Provider: "openrouter",
		APIModel: "fish-audio/s2.1-pro-free:free",
		Currency: "USD",
	},
	Gemini31FlashTTS: {
		ID:               Gemini31FlashTTS,
		Name:             "OpenRouter – Gemini 3.1 Flash TTS Preview",
		Provider:         "openrouter",
		APIModel:         "google/gemini-3.1-flash-tts-preview",
		Currency:         "USD",
		CostPer1MChars:   1,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	Gemini38FlashLiteTTS: {
		ID:       Gemini38FlashLiteTTS,
		Name:     "OpenRouter – Gemini 3.8 Flash Lite TTS",
		Provider: "openrouter",
		APIModel: "google/gemini-3.8-flash-lite-tts",
		Currency: "USD",
	},
	Gemini38FlashTTS: {
		ID:       Gemini38FlashTTS,
		Name:     "OpenRouter – Gemini 3.8 Flash TTS",
		Provider: "openrouter",
		APIModel: "google/gemini-3.8-flash-tts",
		Currency: "USD",
	},
	Kokoro82M: {
		ID:               Kokoro82M,
		Name:             "OpenRouter – Kokoro 82M",
		Provider:         "openrouter",
		APIModel:         "hexgrad/kokoro-82m",
		Currency:         "USD",
		CostPer1MChars:   0.62,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MAIVoice2: {
		ID:               MAIVoice2,
		Name:             "OpenRouter – MAI-Voice-2",
		Provider:         "openrouter",
		APIModel:         "microsoft/mai-voice-2",
		Currency:         "USD",
		CostPer1MChars:   22,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MAIVoice2Flash: {
		ID:               MAIVoice2Flash,
		Name:             "OpenRouter – MAI-Voice-2-Flash",
		Provider:         "openrouter",
		APIModel:         "microsoft/mai-voice-2-flash",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MaiVoice21: {
		ID:       MaiVoice21,
		Name:     "OpenRouter – MAI-Voice-2.1",
		Provider: "openrouter",
		APIModel: "microsoft/mai-voice-2.1",
		Currency: "USD",
	},
	MaiVoice21Flash: {
		ID:       MaiVoice21Flash,
		Name:     "OpenRouter – MAI-Voice-2.1-Flash",
		Provider: "openrouter",
		APIModel: "microsoft/mai-voice-2.1-flash",
		Currency: "USD",
	},
	MiniMaxSpeech28HD: {
		ID:               MiniMaxSpeech28HD,
		Name:             "OpenRouter – Speech 2.8 HD",
		Provider:         "openrouter",
		APIModel:         "minimax/speech-2.8-hd",
		Currency:         "USD",
		CostPer1MChars:   100,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	MiniMaxSpeech28Turbo: {
		ID:               MiniMaxSpeech28Turbo,
		Name:             "OpenRouter – Speech 2.8 Turbo",
		Provider:         "openrouter",
		APIModel:         "minimax/speech-2.8-turbo",
		Currency:         "USD",
		CostPer1MChars:   60,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	VoxtralMiniTTS: {
		ID:               VoxtralMiniTTS,
		Name:             "OpenRouter – Voxtral Mini TTS",
		Provider:         "openrouter",
		APIModel:         "mistralai/voxtral-mini-tts-2603",
		Currency:         "USD",
		CostPer1MChars:   16,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	QwenAudio3TTSFlash: {
		ID:               QwenAudio3TTSFlash,
		Name:             "OpenRouter – Qwen-Audio-3.0-TTS Flash",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-audio-3.0-tts-flash",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	QwenAudio3TTSPlus: {
		ID:               QwenAudio3TTSPlus,
		Name:             "OpenRouter – Qwen-Audio-3.0-TTS Plus",
		Provider:         "openrouter",
		APIModel:         "qwen/qwen-audio-3.0-tts-plus",
		Currency:         "USD",
		CostPer1MChars:   20,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	CSM1B: {
		ID:               CSM1B,
		Name:             "OpenRouter – CSM 1B",
		Provider:         "openrouter",
		APIModel:         "sesame/csm-1b",
		Currency:         "USD",
		CostPer1MChars:   7,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
	GrokVoiceTTS1: {
		ID:               GrokVoiceTTS1,
		Name:             "OpenRouter – Grok Voice TTS 1.0",
		Provider:         "openrouter",
		APIModel:         "x-ai/grok-voice-tts-1.0",
		Currency:         "USD",
		CostPer1MChars:   15,
		SupportedFormats: []string{"mp3", "pcm"},
		DefaultFormat:    "pcm",
	},
}
