// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-20
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// cerebras provider.
//
// Models the index stops listing are removed from this catalog.
// Display names are set when a model is first added and carried over
// from then on.

package cerebras

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Gemma431B  string = "cerebras.gemma-4-31b"
	GPTOss120B string = "cerebras.gpt-oss-120b"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Gemma431B: {
		ID:                    Gemma431B,
		Name:                  "Gemma 4 31B IT",
		Provider:              "cerebras",
		APIModel:              "gemma-4-31b",
		Currency:              "USD",
		CostPer1MIn:           0.99,
		CostPer1MOut:          1.49,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	GPTOss120B: {
		ID:                    GPTOss120B,
		Name:                  "Cerebras – GPT-OSS 120B",
		Provider:              "cerebras",
		APIModel:              "gpt-oss-120b",
		Currency:              "USD",
		CostPer1MIn:           0.35,
		CostPer1MOut:          0.75,
		ContextWindow:         131072,
		DefaultMaxTokens:      40960,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
