// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-10-08
//
// Rates are per 1000 invocations, in the currency the provider
// bills in. A tool's own tokens are billed separately, at the
// calling model's rates, and are not included here.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package openai

import (
	"github.com/joakimcarlsson/ai/hostedtool"
)

// Model IDs served by this catalog.
const (
	AgentKit   string = "agent-kit"
	Containers string = "containers"
	FileSearch string = "file-search"
	WebSearch  string = "web-search"
)

// Models maps model IDs to their configurations.
var Models = map[string]hostedtool.Tool{
	AgentKit: {
		ID:       AgentKit,
		Name:     "Agent Kit",
		Provider: "openai",
		APIModel: "agent-kit",
		Currency: "USD",
	},
	Containers: {
		ID:       Containers,
		Name:     "Containers",
		Provider: "openai",
		APIModel: "containers",
		Currency: "USD",
	},
	FileSearch: {
		ID:             FileSearch,
		Name:           "File search",
		Provider:       "openai",
		APIModel:       "file-search",
		Currency:       "USD",
		CostPer1KCalls: 2.5,
	},
	WebSearch: {
		ID:             WebSearch,
		Name:           "Web search",
		Provider:       "openai",
		APIModel:       "web-search",
		Currency:       "USD",
		CostPer1KCalls: 10,
	},
}
