// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-20
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// deepseek provider.
//
// Models the index stops listing are removed from this catalog.
// Display names are set when a model is first added and carried over
// from then on.

package deepseek

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	DeepseekChat     string = "deepseek-chat"
	DeepseekReasoner string = "deepseek-reasoner"
	V4Flash          string = "deepseek-v4-flash"
	V4Pro            string = "deepseek-v4-pro"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	DeepseekChat: {
		ID:                  DeepseekChat,
		Name:                "DeepSeek Chat",
		Provider:            "deepseek",
		APIModel:            "deepseek-chat",
		Currency:            "USD",
		CostPer1MIn:         0.14,
		CostPer1MOut:        0.28,
		CostPer1MInCached:   0.0028,
		ContextWindow:       1000000,
		DefaultMaxTokens:    384000,
		SupportsAttachments: true,
	},
	DeepseekReasoner: {
		ID:                  DeepseekReasoner,
		Name:                "DeepSeek Reasoner",
		Provider:            "deepseek",
		APIModel:            "deepseek-reasoner",
		Currency:            "USD",
		CostPer1MIn:         0.14,
		CostPer1MOut:        0.28,
		CostPer1MInCached:   0.0028,
		ContextWindow:       1000000,
		DefaultMaxTokens:    384000,
		CanReason:           true,
		SupportsAttachments: true,
	},
	V4Flash: {
		ID:                    V4Flash,
		Name:                  "DeepSeek V4 Flash",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-flash",
		Currency:              "USD",
		CostPer1MIn:           0.14,
		CostPer1MOut:          0.28,
		CostPer1MInCached:     0.0028,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
	V4Pro: {
		ID:                    V4Pro,
		Name:                  "DeepSeek V4 Pro",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-pro",
		Currency:              "USD",
		CostPer1MIn:           0.435,
		CostPer1MOut:          0.87,
		CostPer1MInCached:     0.003625,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsStructuredOut: true,
	},
}
