// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-09-11
//
// Rates are per 1M tokens, in the currency the provider bills in.
// Context windows and output limits are taken from the same entry.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package deepseek

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	DeepseekFlash1 string = "deepseek-flash (1)"
	DeepseekV4Pro2 string = "deepseek-v4-pro (2)"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	DeepseekFlash1: {
		ID:                    DeepseekFlash1,
		Name:                  "",
		Provider:              "deepseek",
		APIModel:              "deepseek-flash (1)",
		Currency:              "USD",
		CostPer1MIn:           0.15,
		CostPer1MOut:          0.6,
		CostPer1MInCached:     0.003,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
	DeepseekV4Pro2: {
		ID:                    DeepseekV4Pro2,
		Name:                  "",
		Provider:              "deepseek",
		APIModel:              "deepseek-v4-pro (2)",
		Currency:              "USD",
		CostPer1MIn:           0.66,
		CostPer1MOut:          1.98,
		CostPer1MInCached:     0.022,
		ContextWindow:         1000000,
		DefaultMaxTokens:      384000,
		CanReason:             true,
		SupportsAttachments:   true,
		SupportsStructuredOut: true,
	},
}
