// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://models.dev/api.json
// Generated: 2026-08-20
//
// Rates are USD per 1M tokens, as models.dev indexes them for the
// perplexity provider.
//
// Models the index stops listing are removed from this catalog.
// Display names are set when a model is first added and carried over
// from then on.

package perplexity

import (
	"github.com/joakimcarlsson/ai/llm"
)

// Model IDs served by this catalog.
const (
	Sonar             string = "sonar"
	SonarDeepResearch string = "sonar-deep-research"
	SonarPro          string = "sonar-pro"
	SonarReasoningPro string = "sonar-reasoning-pro"
)

// Models maps model IDs to their configurations.
var Models = map[string]llm.Model{
	Sonar: {
		ID:               Sonar,
		Name:             "Sonar",
		Provider:         "perplexity",
		APIModel:         "sonar",
		Currency:         "USD",
		CostPer1MIn:      1,
		CostPer1MOut:     1,
		ContextWindow:    128000,
		DefaultMaxTokens: 4096,
	},
	SonarDeepResearch: {
		ID:               SonarDeepResearch,
		Name:             "Sonar Deep Research",
		Provider:         "perplexity",
		APIModel:         "sonar-deep-research",
		Currency:         "USD",
		CostPer1MIn:      2,
		CostPer1MOut:     8,
		ContextWindow:    128000,
		DefaultMaxTokens: 32768,
		CanReason:        true,
	},
	SonarPro: {
		ID:                  SonarPro,
		Name:                "Sonar Pro",
		Provider:            "perplexity",
		APIModel:            "sonar-pro",
		Currency:            "USD",
		CostPer1MIn:         3,
		CostPer1MOut:        15,
		ContextWindow:       200000,
		DefaultMaxTokens:    8192,
		SupportsAttachments: true,
	},
	SonarReasoningPro: {
		ID:                  SonarReasoningPro,
		Name:                "Sonar Reasoning Pro",
		Provider:            "perplexity",
		APIModel:            "sonar-reasoning-pro",
		Currency:            "USD",
		CostPer1MIn:         2,
		CostPer1MOut:        8,
		ContextWindow:       128000,
		DefaultMaxTokens:    4096,
		CanReason:           true,
		SupportsAttachments: true,
	},
}
