// Code generated by cmd/modelsync. DO NOT EDIT.
//
// Source: https://github.com/JoakimCarlsson/model-sync (api.json)
// Generated: 2026-10-01
//
// CostPer1MChars is per 1M characters, in the currency the provider
// bills in. Default format and latency are not published and are
// carried over from the previous catalog.
//
// A model the source stops listing is removed from this catalog.
// Display names and anything the source does not publish are set when a
// model is first added and carried over from then on.

package google

import (
	"github.com/joakimcarlsson/ai/tts"
)

// Model IDs served by this catalog.
const (
	Gemini25FlashPreviewTTS string = "gemini-2.5-flash-preview-tts"
	Gemini25ProPreviewTTS   string = "gemini-2.5-pro-preview-tts"
	Gemini31FlashTTSPreview string = "gemini-3.1-flash-tts-preview"
	Gemini38FlashLiteTTS    string = "gemini-3.8-flash-lite-tts"
	Gemini38FlashTTS        string = "gemini-3.8-flash-tts"
)

// Models maps model IDs to their configurations.
var Models = map[string]tts.AudioModel{
	Gemini25FlashPreviewTTS: {
		ID:       Gemini25FlashPreviewTTS,
		Name:     "Gemini 2.5 Flash Preview TTS",
		Provider: "google-cloud",
		APIModel: "gemini-2.5-flash-preview-tts",
		Currency: "USD",
	},
	Gemini25ProPreviewTTS: {
		ID:       Gemini25ProPreviewTTS,
		Name:     "Gemini 2.5 Pro Preview TTS",
		Provider: "google-cloud",
		APIModel: "gemini-2.5-pro-preview-tts",
		Currency: "USD",
	},
	Gemini31FlashTTSPreview: {
		ID:       Gemini31FlashTTSPreview,
		Name:     "Gemini 3.1 Flash TTS Preview",
		Provider: "google-cloud",
		APIModel: "gemini-3.1-flash-tts-preview",
		Currency: "USD",
	},
	Gemini38FlashLiteTTS: {
		ID:       Gemini38FlashLiteTTS,
		Name:     "Gemini 3.8 Flash-Lite TTS",
		Provider: "google-cloud",
		APIModel: "gemini-3.8-flash-lite-tts",
		Currency: "USD",
	},
	Gemini38FlashTTS: {
		ID:       Gemini38FlashTTS,
		Name:     "Gemini 3.8 Flash TTS",
		Provider: "google-cloud",
		APIModel: "gemini-3.8-flash-tts",
		Currency: "USD",
	},
}
